version: '3.8'
services:
  app:
    image: watchmovie:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watchmovie-bo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/watchmovie
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 111111
    depends_on:
      - db

  # mysql
  db:
      image: mysql:8.0
      container_name: mysql-db
      environment:
        MYSQL_ROOT_PASSWORD: 111111
        MYSQL_DATABASE: watchmovie
        MYSQL_USER: root
        MYSQL_PASSWORD: 111111
      ports:
        - "3307:3306"
      volumes:
        - mysql-data:/var/lib/mysql

volumes:
    mysql-data:

